# Generated by Django 2.2 on 2020-09-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbAdministradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administradoraNome', models.CharField(blank=50, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Administradora',
                'db_table': 'tbAdministradora',
            },
        ),
        migrations.CreateModel(
            name='tbCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidadeNome', models.CharField(blank=True, max_length=50, null=True)),
                ('cidadeEstado', models.CharField(blank=True, max_length=50, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cidade',
                'db_table': 'tbCidade',
            },
        ),
        migrations.CreateModel(
            name='tbCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteNome', models.CharField(blank=True, max_length=50, null=True)),
                ('clienteAdministrador', models.CharField(blank=True, max_length=20, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'tbCliente',
            },
        ),
        migrations.CreateModel(
            name='tbEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamentoNome', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoQrCode', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoObservacao', models.CharField(blank=True, max_length=255, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'tbEquipamento',
            },
        ),
        migrations.CreateModel(
            name='tbPreventivas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventivaEquipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('preventivaProcedimento', models.CharField(blank=True, max_length=255, null=True)),
                ('preventivaTempo', models.IntegerField(blank=True, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Preventivas',
                'db_table': 'tbPreventivas',
            },
        ),
        migrations.CreateModel(
            name='tbSenhasPadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senhaLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaObservacao', models.CharField(blank=True, max_length=255, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Senhas Padrões',
                'db_table': 'tbSenhasPadores',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaCftv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaCftvNome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de CFTV',
                'db_table': 'tbSistemaCftv',
            },
        ),
        migrations.CreateModel(
            name='tbSistemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemasTipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
                'db_table': 'tbSistemas',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSaiNome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SAI',
                'db_table': 'tbSistemaSai',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSapNome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SAP',
                'db_table': 'tbSistemaSap',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaScaNome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SCA',
                'db_table': 'tbSistemaSca',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSdai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSdaiNome', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SDAI',
                'db_table': 'tbSistemaSdai',
            },
        ),
        migrations.CreateModel(
            name='tbWework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weworkNome', models.CharField(blank=True, max_length=50, null=True)),
                ('weworkQuantAndares', models.IntegerField(blank=True, null=True)),
                ('weworkAndares', models.CharField(blank=True, max_length=50, null=True)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Weworks',
                'db_table': 'tbWework',
            },
        ),
    ]
