# Generated by Django 3.0 on 2020-09-19 16:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbAdministradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administradora', models.CharField(blank=50, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Administradora',
                'db_table': 'tbAdministradora',
            },
        ),
        migrations.CreateModel(
            name='tbArtigos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigoTitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('artigoSubtitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('artigoTexto', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artigos',
                'db_table': 'tbArtigos',
            },
        ),
        migrations.CreateModel(
            name='tbCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('cidadeEstado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cidade',
                'db_table': 'tbCidade',
            },
        ),
        migrations.CreateModel(
            name='tbCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteNome', models.CharField(blank=True, max_length=50, null=True)),
                ('clienteAdministrador', models.CharField(blank=True, max_length=20, null=True)),
                ('clienteObservacao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('clienteAdministradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbAdministradora')),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'tbCliente',
            },
        ),
        migrations.CreateModel(
            name='tbFabricante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaFabricante', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema Fabricante',
                'db_table': 'tbFabricante',
            },
        ),
        migrations.CreateModel(
            name='tbPreventivas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventivaEquipamento', models.CharField(blank=True, max_length=100, null=True)),
                ('preventivaProcedimento', models.CharField(blank=True, max_length=255, null=True)),
                ('preventivaTempo', models.IntegerField(blank=True, null=True)),
                ('preventivaObservacao', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Preventivas',
                'db_table': 'tbPreventivas',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaCftv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaCftv', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de CFTV',
                'db_table': 'tbSistemaCftv',
            },
        ),
        migrations.CreateModel(
            name='tbSistemas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemasTipo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistemas',
                'db_table': 'tbSistemas',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSai', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SAI',
                'db_table': 'tbSistemaSai',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSap', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SAP',
                'db_table': 'tbSistemaSap',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSca', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SCA',
                'db_table': 'tbSistemaSca',
            },
        ),
        migrations.CreateModel(
            name='tbSistemaSdai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistemaSdai', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sistema de SDAI',
                'db_table': 'tbSistemaSdai',
            },
        ),
        migrations.CreateModel(
            name='tbWework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wework', models.CharField(blank=True, max_length=50, null=True)),
                ('weworkQuantAndares', models.IntegerField(blank=True, null=True)),
                ('weworkAndares', models.CharField(blank=True, max_length=50, null=True)),
                ('weworkCondominio', models.CharField(blank=True, max_length=100, null=True)),
                ('weworkSdai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaSdai')),
            ],
            options={
                'verbose_name_plural': 'Weworks',
                'db_table': 'tbWework',
            },
        ),
        migrations.CreateModel(
            name='tbSenhasPadroes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senhaEquipamento', models.CharField(blank=True, max_length=255, null=True)),
                ('senhaLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('senhaFabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbFabricante')),
            ],
            options={
                'verbose_name_plural': 'Senhas Padrões',
                'db_table': 'tbSenhasPadroes',
            },
        ),
        migrations.CreateModel(
            name='tbManuais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manualNome', models.CharField(blank=True, max_length=100, null=True)),
                ('manualLink', models.CharField(blank=True, max_length=255, null=True)),
                ('manualFabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbFabricante')),
                ('manualSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemas')),
            ],
            options={
                'verbose_name_plural': 'Manuais',
                'db_table': 'tbManuais',
            },
        ),
        migrations.CreateModel(
            name='tbEquipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipamento', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoLogin', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoPassword', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoQrCode', models.CharField(blank=True, max_length=50, null=True)),
                ('equipamentoObservacao', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('equipamentoCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbCliente')),
                ('equipamentoSistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemas')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
                'db_table': 'tbEquipamento',
            },
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteCftv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaCftv'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteCidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbCidade'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteSai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaSai'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteSap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaSap'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteSca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaSca'),
        ),
        migrations.AddField(
            model_name='tbcliente',
            name='clienteSdai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbSistemaSdai'),
        ),
    ]
