# Generated by Django 3.0 on 2020-09-19 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbSenhasPadroes',
            new_name='tbSenhasPadroess',
        ),
    ]
