# Generated by Django 3.0 on 2020-09-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbcliente',
            name='clienteAdministradora',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
