# Generated by Django 2.0 on 2020-09-21 14:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbartigos',
            name='artigoTexto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
