# Generated by Django 3.0 on 2020-09-21 16:50

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0003_tbpreventivas_manualsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbmanuais',
            name='manualDescricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tbpreventivas',
            name='preventivaProcedimento',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
