# Generated by Django 3.0 on 2020-10-22 00:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0005_tbwework_clientecidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbSapScirp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quadroSap', models.CharField(blank=True, max_length=50, null=True)),
                ('gerenciadora', models.CharField(choices=[('BCX_SUP_01', 'BCX_SUP_01'), ('BCX_SUP_02', 'BCX_SUP_02'), ('BCX_2SS_01', 'BCX_2SS_01'), ('NET_SUP_01', 'NET_SUP_01'), ('NET_2SS_01', 'NET_2SS_01')], max_length=255)),
                ('statusSap', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('quantidadeControladoras', models.IntegerField(blank=True, null=True)),
                ('observacoesSap', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quadros SCIRP',
                'db_table': 'tbSapScirp',
            },
        ),
    ]
