# Generated by Django 3.0 on 2020-10-29 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0006_tbsapscirp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbCameraIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCamera', models.CharField(blank=True, max_length=255, null=True)),
                ('numeroCamera', models.IntegerField(blank=True, null=True)),
                ('numeroIp', models.CharField(blank=True, max_length=20, null=True)),
                ('fabricanteCamera', models.CharField(choices=[('Axis', 'Axis'), ('Interlbras', 'Intelbras')], max_length=255)),
                ('loginCamera', models.CharField(blank=True, max_length=20, null=True)),
                ('senhaCamera', models.CharField(blank=True, max_length=20, null=True)),
                ('equipamentoGravacao', models.CharField(choices=[('DVR1', 'DVR1'), ('DVR2', 'DVR2'), ('DVR3', 'DVR3'), ('NVR1', 'NVR1'), ('NVR2', 'NVR2'), ('NVR3', 'NVR3'), ('VAU1', 'VAU1'), ('VAU2', 'VAU2'), ('VAU3', 'VAU3')], max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evertical.tbCliente')),
            ],
            options={
                'verbose_name_plural': 'Câmeras IP',
                'db_table': 'tbCameraIp',
            },
        ),
    ]
