# Generated by Django 3.0 on 2020-11-19 13:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evertical', '0008_auto_20201029_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbsapscirp',
            name='atualizacao',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 11, 19, 13, 34, 11, 807681, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbsapscirp',
            name='quadroIluminacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
